version: "3.9"
services:
 sqlserver:
  image: mcr.microsoft.com/mssql/server:2019-latest
  container_name: sql_server_2019
  restart: always
  volumes:
   - docker_sqlserver_systemdbs:/var/opt/mssql/
   - docker_sqlserver_userdbs:/var/opt/sqlserver
   - docker_sqlserver_mssqltools:/var/opt/mssql-tools/bin
  environment:
   - SA_PASSWORD=!A123456
   - ACCEPT_EULA=Y
   - MinProtocol=TLSv1
   - CipherString=DEFAULT@SECLEVEL=1
   - TrustServerCertificate=True
   - Encrypt=True
  ports:
   - 1433:1433
  networks:
   - sqlserver_network

networks:
 sqlserver_network:
  driver: bridge

volumes:
 docker_sqlserver_systemdbs:
  driver: local
 docker_sqlserver_userdbs:
  driver: local
 docker_sqlserver_mssqltools:
  driver: local